// Generated by jextract

package com.nvidia.cuopt.internal.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*cuOptMIPGetSolutionCallback)(const cuopt_float_t *, const cuopt_float_t *, const cuopt_float_t *, void *)
 * }
 */
public class cuOptMIPGetSolutionCallback {

    cuOptMIPGetSolutionCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment solution, MemorySegment objective_value, MemorySegment solution_bound, MemorySegment user_data);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        cuopt_c_h.C_POINTER,
        cuopt_c_h.C_POINTER,
        cuopt_c_h.C_POINTER,
        cuopt_c_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = cuopt_c_h.upcallHandle(cuOptMIPGetSolutionCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(cuOptMIPGetSolutionCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,MemorySegment solution, MemorySegment objective_value, MemorySegment solution_bound, MemorySegment user_data) {
        try {
             DOWN$MH.invokeExact(funcPtr, solution, objective_value, solution_bound, user_data);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
