c_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

cxx_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

cuda_compiler:
  - cuda-nvcc  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - nvcc  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

c_stdlib:
  - sysroot

c_stdlib_version:
  - "=2.28"

cmake_version:
  - ">=3.30.4"

gtest_version:
  - ">=1.13.0"

cuda11_libcurand_host_version:
  - "=10.3.0.86"