#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

# Determine whether a test should run based on the label map generated by CMake.
# The label map file (test_component_labels.txt) contains lines like:
#   ROUTING_TEST:routing
#   LP_UNIT_TEST:lp
#   CLI_TEST:shared
# Tests labelled "shared" always run. Unknown tests (not in the map) also run.
should_run_test() {
    local test_name="$1"
    local components="${CUOPT_TEST_COMPONENTS:-all}"

    if [[ "${components}" == "all" ]]; then
        return 0
    fi

    # Look up the label from the map file
    local label=""
    if [[ -n "${LABEL_MAP_FILE:-}" && -f "${LABEL_MAP_FILE}" ]]; then
        label=$(grep "^${test_name}:" "${LABEL_MAP_FILE}" 2>/dev/null | cut -d: -f2 || true)
    fi

    # "shared" or unknown tests always run
    if [[ -z "${label}" || "${label}" == "shared" ]]; then
        return 0
    fi

    # Check if the test's label is in the requested components
    # MIP tests also run when LP is requested (MIP depends on LP infrastructure)
    if [[ "${components}" == *"${label}"* ]]; then
        return 0
    fi

    return 1
}

# Support customizing the gtests' install location
# First, try the installed location (CI/conda environments)
installed_test_location="${INSTALL_PREFIX:-${CONDA_PREFIX:-/usr}}/bin/gtests/libcuopt/"
# Fall back to the build directory (devcontainer environments)
devcontainers_test_location="$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../cpp/build/latest/gtests/libcuopt/"

if [[ -d "${installed_test_location}" ]]; then
    GTEST_DIR="${installed_test_location}"
elif [[ -d "${devcontainers_test_location}" ]]; then
    GTEST_DIR="${devcontainers_test_location}"
else
    echo "Error: Test location not found. Searched:" >&2
    echo "  - ${installed_test_location}" >&2
    echo "  - ${devcontainers_test_location}" >&2
    exit 1
fi

# Load the label map if available
LABEL_MAP_FILE="${GTEST_DIR}/test_component_labels.txt"
if [[ ! -f "${LABEL_MAP_FILE}" ]]; then
    echo "Warning: Label map not found at ${LABEL_MAP_FILE}, all tests will run." >&2
    LABEL_MAP_FILE=""
fi

for gt in "${GTEST_DIR}"/*_TEST; do
    test_name=$(basename "${gt}")
    if should_run_test "${test_name}"; then
        echo "Running gtest ${test_name}"
        "${gt}" "$@"
    else
        echo "Skipping gtest ${test_name} (not in CUOPT_TEST_COMPONENTS=${CUOPT_TEST_COMPONENTS:-all})"
    fi
done

# Run C_API_TEST with CPU memory for local solves (excluding time limit tests)
if [ -x "${GTEST_DIR}/C_API_TEST" ] && should_run_test "C_API_TEST"; then
  echo "Running gtest C_API_TEST with CUOPT_USE_CPU_MEM_FOR_LOCAL"
  CUOPT_USE_CPU_MEM_FOR_LOCAL=1 "${GTEST_DIR}/C_API_TEST" --gtest_filter=-c_api/TimeLimitTestFixture.* "$@"
else
  echo "Skipping C_API_TEST with CUOPT_USE_CPU_MEM_FOR_LOCAL"
fi
