# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: cloud_ci_checker
on:
  push:
    branches:
      - ${GITHUB_REF##*/}
    paths:
      - 'cloud-scripts'

permissions: {}

jobs:
  conditional_step:
    permissions:
      contents: read
    runs-on: 'ubuntu-22.04'
    steps:
      - run: echo "Starting GitHub Actions Job for Cloud CI test notification"
      - uses: cinotify/github-action@89d5abbbfb50cdba9d4b462d47d9378d7d204d75 # main
        with:
          to: 'cuopt-eng@nvidia.com'
          subject: 'Cloud scripts change notification'
          body: 'This is a notification from GitHub actions.'
