name: Trigger Nightly cuOpt Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST


        echo "RAPIDS_REPOSITORY=${{ inputs.repo || github.repository }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        sha="${{ inputs.sha }}"
        if [[ "${sha}" == "" ]]; then
          sha=$(git rev-parse HEAD)
        fi
        echo "RAPIDS_SHA=${sha}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_REF_NAME=${{ inputs.branch || github.ref_name }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_NIGHTLY_DATE=${{ inputs.date }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        if [[ -n "${{ inputs.build_workflow_name }}" ]]; then
          echo "RAPIDS_BUILD_WORKFLOW_NAME=${{ inputs.build_workflow_name }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        fi

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuopt_version: "25.10"
jobs:
  get-run-info:
    runs-on: ubuntu-latest
    shell: bash
    run: |
      BRANCHES=(
        branch-25.10
      )
      for 

      # latest commit on each branch
      export RAPIDS_SHA="$(git ls-remote ${{ github.repositoryUrl }} refs/heads/${{ }} | awk '{print $1}')"
  build:
    uses: ./.github/workflows/build.yaml
    with:
      build_type: nightly
      branch: branch-${{ matrix.cuopt_version }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
  test:
    needs: build
    uses: ./.github/workflows/test.yaml
    with:
      build_type: nightly
      branch: branch-${{ matrix.cuopt_version }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
