name: Trigger Nightly cuOpt Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST

jobs:
  compute-matrix:
    id: compute-matrix
    runs-on: ubuntu-latest
    steps:
      - name: compute-matrix
        shell: bash
        run: |
          # add more list items here to run nightlies for more branches
          export CI_MATRIX="
          - branch: '25.10'
            sha: "\'$(git ls-remote ${{ github.repositoryUrl }} refs/heads/branch-25.10 | awk '{print $1}')\'"
          "
          MATRIX="$(
            yq -n -o json 'env(CI_MATRIX)' | \
          )"

          echo "MATRIX=${MATRIX}" | tee --append "${GITHUB_OUTPUT}"
          echo "date=$(date +%F)" | tee --append "${GITHUB_OUTPUT}"
  build:
    needs: [compute-matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    uses: ./.github/workflows/build.yaml
    with:
      build_type: nightly
      branch: ${{ matrix.branch }}
      date: ${{ needs.compute-matrix.outputs.date }}
      sha: ${{ matrix.sha }}
  test:
    needs: [compute-matrix, build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.compute-matrix.outputs.MATRIX) }}
    uses: ./.github/workflows/test.yaml
    with:
      build_type: nightly
      branch: ${{ matrix.branch }}
      date: ${{ needs.compute-matrix.outputs.date }}
      sha: ${{ matrix.sha }}
