name: Trigger Nightly cuOpt Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST


jobs:
  trigger-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuopt_version: "25.05"
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Pipeline
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          export CUOPT_BRANCH="branch-${{ matrix.cuopt_version }}"
          export DATE=$(date +%F)
          export SHA=$(gh api -q '.commit.sha' "repos/nvidia/cuopt/branches/${CUOPT_BRANCH}")

          gh workflow run build.yaml \
            -f branch="${CUOPT_BRANCH}" \
            -f sha="${SHA}" \
            -f date="${DATE}" \
            -f build_type=nightly

          # Wait a short bit for the workflow to register (optional)
          sleep 3

          # Get the latest run ID for this workflow on this branch
          RUN_ID=$(gh run list --workflow=build.yaml --branch="${CUOPT_BRANCH}" --json databaseId --limit 1 | jq -r '.[0].databaseId')

          # Wait for workflow to complete
          gh run watch "$RUN_ID"

  trigger-test:
    runs-on: ubuntu-latest
    needs: trigger-build
    strategy:
      matrix:
        include:
          - cuopt_version: "25.05"
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Test
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          export CUOPT_BRANCH="branch-${{ matrix.cuopt_version }}"
          export DATE=$(date +%F)
          export SHA=$(gh api -q '.commit.sha' "repos/nvidia/cuopt/branches/${CUOPT_BRANCH}")

          gh workflow run test.yaml \
            -f branch=${CUOPT_BRANCH} \
            -f sha=${SHA} \
            -f date=${DATE} \
            -f build_type=nightly


