# SPDX-FileCopyrightText: Copyright (c) 2021-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@secrets

  checks:
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@secrets
    with:
      enable_check_generated_files: false
    secrets:
      script-env-secret-1-key: MY_COOL_SECRET_NAME
      script-env-secret-1-value: ${{ secrets.TEST_NAME }}
      script-env-secret-2-key: MY_COOL_SECRET_PASSWORD
      script-env-secret-2-value: ${{ secrets.TEST_PASSWORD }}
