name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
        #- conda-cpp-build
        #- conda-cpp-tests
        #- conda-python-build
        #- conda-python-tests
      - wheel-build-libcuopt
        # - conda-notebook-tests
        #- wheel-build-cuopt
        #- wheel-tests-cuopt
        #- wheel-build-cuopt-server
        #- wheel-tests-cuopt-server
      - wheel-build-cuopt-mps-parser
        #- wheel-build-cuopt-sh-client
        #- test-self-hosted-server
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-25.08
  wheel-build-cuopt-mps-parser:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      build_type: pull-request
      script: ci/build_wheel_cuopt_mps_parser.sh
      package-name: cuopt_mps_parser
      package-type: python
      append-cuda-suffix: false
      matrix_filter: map(select((.CUDA_VER | startswith("12"))))
  wheel-build-libcuopt:
    needs: wheel-build-cuopt-mps-parser
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-25.08
    with:
      # build for amd64 architecture only with CUDA 12 and latest Python
      matrix_filter: map(select((.CUDA_VER | startswith("12")) and .PY_VER == "3.13" and .ARCH == "amd64"))
      package-type: cpp
      package-name: libcuopt
      build_type: pull-request
      script: ci/build_wheel_libcuopt.sh
