name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build_type:
        type: string
        default: nightly

jobs:
  conda-cpp-tests:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@branch-25.08
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      matrix_filter: map(select((.CUDA_VER | startswith("12")) and .PY_VER != "3.13"))
      script: ci/test_cpp.sh
  conda-python-tests:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@branch-25.08
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      matrix_filter: map(select((.CUDA_VER | startswith("12")) and .PY_VER != "3.13"))
      script: ci/test_python.sh
  wheel-tests-cuopt:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-25.08
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      matrix_filter: map(select((.CUDA_VER | startswith("12")) and .PY_VER != "3.13"))
      script: ci/test_wheel_cuopt.sh
  wheel-tests-cuopt-server:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-25.08
    with:
      build_type: ${{ inputs.build_type }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
      matrix_filter: map(select((.CUDA_VER | startswith("12")) and .PY_VER != "3.13"))
      script: ci/test_wheel_cuopt_server.sh
